<script setup>
</script>

<template>
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Anima Project - Automatically generated by Anima</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      @font-face {
        font-family: "Molot-Regular";
        src: url("https://anima-uploads.s3.amazonaws.com/5d520a008757aedef3ee25d1/Molot.otf") format("opentype");
      }

      @font-face {
        font-family: "Century-Regular";
        src: url("https://anima-uploads.s3.amazonaws.com/projects/6107191e4a92f15de20d4652/fonts/centaur-regular.ttf")
        format("truetype");
      }
    </style>
    <style>
      @import url("https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css");
      * {
        -webkit-font-smoothing: antialiased;
        box-sizing: border-box;
      }
      html,
      body {
        margin: 0px;
        height: 100%;
      }
      /* a blue color as a generic focus style */
      button:focus-visible {
        outline: 2px solid #4a90e2 !important;
        outline: -webkit-focus-ring-color auto 5px !important;
      }
      a {
        text-decoration: none;
      }
    </style>
    <link href="styleguide.css" rel="stylesheet" />
  </head>
  <body>
  <noscript>
    <strong
    >We're sorry but codesandbox doesn't work properly without JavaScript
      enabled. Please enable it to continue.</strong
    >
  </noscript>
  <div id="app"></div>
  <router-view></router-view>
  </body>
  </html>
</template>
